// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.payload.multipart.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;

/**
 * The FileWithHttpPartSpecificContentTypeRequest model.
 */
@Immutable
public final class FileWithHttpPartSpecificContentTypeRequest {
    /*
     * The profileImage property.
     */
    @Generated
    private final FileSpecificContentTypeFileDetails profileImage;

    /**
     * Creates an instance of FileWithHttpPartSpecificContentTypeRequest class.
     * 
     * @param profileImage the profileImage value to set.
     */
    @Generated
    public FileWithHttpPartSpecificContentTypeRequest(FileSpecificContentTypeFileDetails profileImage) {
        this.profileImage = profileImage;
    }

    /**
     * Get the profileImage property: The profileImage property.
     * 
     * @return the profileImage value.
     */
    @Generated
    public FileSpecificContentTypeFileDetails getProfileImage() {
        return this.profileImage;
    }
}
