// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

module com.azure.security.confidentialledger {
    requires transitive com.azure.core;

    exports com.azure.security.confidentialledger;
    exports com.azure.security.confidentialledger.models;

    opens com.azure.security.confidentialledger.models to
            com.azure.core,
            com.fasterxml.jackson.databind;
}
