// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.security.confidentialledger.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Defines values for AssignedRole. */
public enum AssignedRole {
    /** Enum value Administrator. */
    ADMINISTRATOR("Administrator"),

    /** Enum value Contributor. */
    CONTRIBUTOR("Contributor"),

    /** Enum value Reader. */
    READER("Reader");

    /** The actual serialized value for a AssignedRole instance. */
    private final String value;

    AssignedRole(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a AssignedRole instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed AssignedRole object, or null if unable to parse.
     */
    @JsonCreator
    public static AssignedRole fromString(String value) {
        AssignedRole[] items = AssignedRole.values();
        for (AssignedRole item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
