// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.security.confidentialledger.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The error object. */
@Immutable
public final class Error {
    /*
     * One of a server-defined set of error codes.
     */
    @JsonProperty(value = "code", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String code;

    /*
     * A human-readable representation of the error.
     */
    @JsonProperty(value = "message", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String message;

    /*
     * The target of the error.
     */
    @JsonProperty(value = "target", access = JsonProperty.Access.WRITE_ONLY)
    private String target;

    /*
     * An array of details about specific errors that led to this reported
     * error.
     */
    @JsonProperty(value = "details", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private Error details;

    /*
     * An object containing more specific information than the current object
     * about the error.
     */
    @JsonProperty(value = "innererror", access = JsonProperty.Access.WRITE_ONLY)
    private InnerError innererror;

    /**
     * Creates an instance of Error class.
     *
     * @param code the code value to set.
     * @param message the message value to set.
     * @param details the details value to set.
     */
    @JsonCreator
    public Error(
            @JsonProperty(value = "code", required = true, access = JsonProperty.Access.WRITE_ONLY) String code,
            @JsonProperty(value = "message", required = true, access = JsonProperty.Access.WRITE_ONLY) String message,
            @JsonProperty(value = "details", required = true, access = JsonProperty.Access.WRITE_ONLY) Error details) {
        this.code = code;
        this.message = message;
        this.details = details;
    }

    /**
     * Get the code property: One of a server-defined set of error codes.
     *
     * @return the code value.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Get the message property: A human-readable representation of the error.
     *
     * @return the message value.
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * Get the target property: The target of the error.
     *
     * @return the target value.
     */
    public String getTarget() {
        return this.target;
    }

    /**
     * Get the details property: An array of details about specific errors that led to this reported error.
     *
     * @return the details value.
     */
    public Error getDetails() {
        return this.details;
    }

    /**
     * Get the innererror property: An object containing more specific information than the current object about the
     * error.
     *
     * @return the innererror value.
     */
    public InnerError getInnererror() {
        return this.innererror;
    }
}
