// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.security.confidentialledger.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An object containing more specific information about the error. As per Microsoft One API guidelines -
 * https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses.
 */
@Immutable
public final class InnerError {
    /*
     * One of a server-defined set of error codes.
     */
    @JsonProperty(value = "code", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String code;

    /*
     * Inner error.
     */
    @JsonProperty(value = "innererror", access = JsonProperty.Access.WRITE_ONLY)
    private InnerError innererror;

    /**
     * Creates an instance of InnerError class.
     *
     * @param code the code value to set.
     */
    @JsonCreator
    public InnerError(
            @JsonProperty(value = "code", required = true, access = JsonProperty.Access.WRITE_ONLY) String code) {
        this.code = code;
    }

    /**
     * Get the code property: One of a server-defined set of error codes.
     *
     * @return the code value.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Get the innererror property: Inner error.
     *
     * @return the innererror value.
     */
    public InnerError getInnererror() {
        return this.innererror;
    }
}
