// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.security.confidentialledger.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The LedgerEntry model. */
@Immutable
public final class LedgerEntry {
    /*
     * The contents property.
     */
    @JsonProperty(value = "contents", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String contents;

    /*
     * The collectionId property.
     */
    @JsonProperty(value = "collectionId", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String collectionId;

    /*
     * The transactionId property.
     */
    @JsonProperty(value = "transactionId", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String transactionId;

    /**
     * Creates an instance of LedgerEntry class.
     *
     * @param contents the contents value to set.
     * @param collectionId the collectionId value to set.
     * @param transactionId the transactionId value to set.
     */
    @JsonCreator
    public LedgerEntry(
            @JsonProperty(value = "contents", required = true, access = JsonProperty.Access.WRITE_ONLY) String contents,
            @JsonProperty(value = "collectionId", required = true, access = JsonProperty.Access.WRITE_ONLY)
                    String collectionId,
            @JsonProperty(value = "transactionId", required = true, access = JsonProperty.Access.WRITE_ONLY)
                    String transactionId) {
        this.contents = contents;
        this.collectionId = collectionId;
        this.transactionId = transactionId;
    }

    /**
     * Get the contents property: The contents property.
     *
     * @return the contents value.
     */
    public String getContents() {
        return this.contents;
    }

    /**
     * Get the collectionId property: The collectionId property.
     *
     * @return the collectionId value.
     */
    public String getCollectionId() {
        return this.collectionId;
    }

    /**
     * Get the transactionId property: The transactionId property.
     *
     * @return the transactionId value.
     */
    public String getTransactionId() {
        return this.transactionId;
    }
}
