// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.security.confidentialledger.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The LedgerUser model. */
@Immutable
public final class LedgerUser {
    /*
     * The assignedRole property.
     */
    @JsonProperty(value = "assignedRole", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private AssignedRole assignedRole;

    /*
     * The userId property.
     */
    @JsonProperty(value = "userId", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String userId;

    /**
     * Creates an instance of LedgerUser class.
     *
     * @param assignedRole the assignedRole value to set.
     * @param userId the userId value to set.
     */
    @JsonCreator
    public LedgerUser(
            @JsonProperty(value = "assignedRole", required = true, access = JsonProperty.Access.WRITE_ONLY)
                    AssignedRole assignedRole,
            @JsonProperty(value = "userId", required = true, access = JsonProperty.Access.WRITE_ONLY) String userId) {
        this.assignedRole = assignedRole;
        this.userId = userId;
    }

    /**
     * Get the assignedRole property: The assignedRole property.
     *
     * @return the assignedRole value.
     */
    public AssignedRole getAssignedRole() {
        return this.assignedRole;
    }

    /**
     * Get the userId property: The userId property.
     *
     * @return the userId value.
     */
    public String getUserId() {
        return this.userId;
    }
}
