// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The AnalyzeTextJobsInput model. */
@Immutable
public final class AnalyzeTextJobsInput {
    /*
     * Optional display name for the analysis job.
     */
    @JsonProperty(value = "displayName", access = JsonProperty.Access.WRITE_ONLY)
    private String displayName;

    /*
     * The analysisInput property.
     */
    @JsonProperty(value = "analysisInput", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private MultiLanguageAnalysisInput analysisInput;

    /*
     * The set of tasks to execute on the input documents.
     */
    @JsonProperty(value = "tasks", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private List<Object> tasks;

    /**
     * Creates an instance of AnalyzeTextJobsInput class.
     *
     * @param analysisInput the analysisInput value to set.
     * @param tasks the tasks value to set.
     */
    @JsonCreator
    public AnalyzeTextJobsInput(
            @JsonProperty(value = "analysisInput", required = true, access = JsonProperty.Access.WRITE_ONLY)
                    MultiLanguageAnalysisInput analysisInput,
            @JsonProperty(value = "tasks", required = true, access = JsonProperty.Access.WRITE_ONLY)
                    List<Object> tasks) {
        this.analysisInput = analysisInput;
        this.tasks = tasks;
    }

    /**
     * Get the displayName property: Optional display name for the analysis job.
     *
     * @return the displayName value.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Get the analysisInput property: The analysisInput property.
     *
     * @return the analysisInput value.
     */
    public MultiLanguageAnalysisInput getAnalysisInput() {
        return this.analysisInput;
    }

    /**
     * Get the tasks property: The set of tasks to execute on the input documents.
     *
     * @return the tasks value.
     */
    public List<Object> getTasks() {
        return this.tasks;
    }
}
