// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/** The AnalyzeTextJobState model. */
@Immutable
public final class AnalyzeTextJobState {
    /*
     * The displayName property.
     */
    @JsonProperty(value = "displayName", access = JsonProperty.Access.WRITE_ONLY)
    private String displayName;

    /*
     * The createdDateTime property.
     */
    @JsonProperty(value = "createdDateTime", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private OffsetDateTime createdDateTime;

    /*
     * The expirationDateTime property.
     */
    @JsonProperty(value = "expirationDateTime", access = JsonProperty.Access.WRITE_ONLY)
    private OffsetDateTime expirationDateTime;

    /*
     * The lastUpdateDateTime property.
     */
    @JsonProperty(value = "lastUpdateDateTime", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private OffsetDateTime lastUpdateDateTime;

    /*
     * The jobId property.
     */
    @JsonProperty(value = "jobId", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String jobId;

    /*
     * The status property.
     */
    @JsonProperty(value = "status", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private Status status;

    /*
     * The errors property.
     */
    @JsonProperty(value = "errors", access = JsonProperty.Access.WRITE_ONLY)
    private List<Error> errors;

    /*
     * The @nextLink property.
     */
    @JsonProperty(value = "@nextLink", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String nextLink;

    /*
     * The tasks property.
     */
    @JsonProperty(value = "tasks", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private TasksStateCounts tasks;

    /*
     * The statistics property.
     */
    @JsonProperty(value = "statistics", access = JsonProperty.Access.WRITE_ONLY)
    private DocumentRequestStatistics statistics;

    /**
     * Creates an instance of AnalyzeTextJobState class.
     *
     * @param createdDateTime the createdDateTime value to set.
     * @param lastUpdateDateTime the lastUpdateDateTime value to set.
     * @param jobId the jobId value to set.
     * @param status the status value to set.
     * @param nextLink the nextLink value to set.
     * @param tasks the tasks value to set.
     */
    @JsonCreator
    public AnalyzeTextJobState(
            @JsonProperty(value = "createdDateTime", required = true, access = JsonProperty.Access.WRITE_ONLY)
                    OffsetDateTime createdDateTime,
            @JsonProperty(value = "lastUpdateDateTime", required = true, access = JsonProperty.Access.WRITE_ONLY)
                    OffsetDateTime lastUpdateDateTime,
            @JsonProperty(value = "jobId", required = true, access = JsonProperty.Access.WRITE_ONLY) String jobId,
            @JsonProperty(value = "status", required = true, access = JsonProperty.Access.WRITE_ONLY) Status status,
            @JsonProperty(value = "@nextLink", required = true, access = JsonProperty.Access.WRITE_ONLY)
                    String nextLink,
            @JsonProperty(value = "tasks", required = true, access = JsonProperty.Access.WRITE_ONLY)
                    TasksStateCounts tasks) {
        this.createdDateTime = createdDateTime;
        this.lastUpdateDateTime = lastUpdateDateTime;
        this.jobId = jobId;
        this.status = status;
        this.nextLink = nextLink;
        this.tasks = tasks;
    }

    /**
     * Get the displayName property: The displayName property.
     *
     * @return the displayName value.
     */
    public String getDisplayName() {
        return this.displayName;
    }

    /**
     * Get the createdDateTime property: The createdDateTime property.
     *
     * @return the createdDateTime value.
     */
    public OffsetDateTime getCreatedDateTime() {
        return this.createdDateTime;
    }

    /**
     * Get the expirationDateTime property: The expirationDateTime property.
     *
     * @return the expirationDateTime value.
     */
    public OffsetDateTime getExpirationDateTime() {
        return this.expirationDateTime;
    }

    /**
     * Get the lastUpdateDateTime property: The lastUpdateDateTime property.
     *
     * @return the lastUpdateDateTime value.
     */
    public OffsetDateTime getLastUpdateDateTime() {
        return this.lastUpdateDateTime;
    }

    /**
     * Get the jobId property: The jobId property.
     *
     * @return the jobId value.
     */
    public String getJobId() {
        return this.jobId;
    }

    /**
     * Get the status property: The status property.
     *
     * @return the status value.
     */
    public Status getStatus() {
        return this.status;
    }

    /**
     * Get the errors property: The errors property.
     *
     * @return the errors value.
     */
    public List<Error> getErrors() {
        return this.errors;
    }

    /**
     * Get the nextLink property: The @nextLink property.
     *
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * Get the tasks property: The tasks property.
     *
     * @return the tasks value.
     */
    public TasksStateCounts getTasks() {
        return this.tasks;
    }

    /**
     * Get the statistics property: The statistics property.
     *
     * @return the statistics value.
     */
    public DocumentRequestStatistics getStatistics() {
        return this.statistics;
    }
}
