// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/** The AnalyzeTextLROResult model. */
@Immutable
public final class AnalyzeTextLROResult {
    /*
     * The taskName property.
     */
    @JsonProperty(value = "taskName", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private String taskName;

    /*
     * The lastUpdateDateTime property.
     */
    @JsonProperty(value = "lastUpdateDateTime", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private OffsetDateTime lastUpdateDateTime;

    /*
     * The status property.
     */
    @JsonProperty(value = "status", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private Status status;

    /**
     * Creates an instance of AnalyzeTextLROResult class.
     *
     * @param taskName the taskName value to set.
     * @param lastUpdateDateTime the lastUpdateDateTime value to set.
     * @param status the status value to set.
     */
    @JsonCreator
    public AnalyzeTextLROResult(
            @JsonProperty(value = "taskName", required = true, access = JsonProperty.Access.WRITE_ONLY) String taskName,
            @JsonProperty(value = "lastUpdateDateTime", required = true, access = JsonProperty.Access.WRITE_ONLY)
                    OffsetDateTime lastUpdateDateTime,
            @JsonProperty(value = "status", required = true, access = JsonProperty.Access.WRITE_ONLY) Status status) {
        this.taskName = taskName;
        this.lastUpdateDateTime = lastUpdateDateTime;
        this.status = status;
    }

    /**
     * Get the taskName property: The taskName property.
     *
     * @return the taskName value.
     */
    public String getTaskName() {
        return this.taskName;
    }

    /**
     * Get the lastUpdateDateTime property: The lastUpdateDateTime property.
     *
     * @return the lastUpdateDateTime value.
     */
    public OffsetDateTime getLastUpdateDateTime() {
        return this.lastUpdateDateTime;
    }

    /**
     * Get the status property: The status property.
     *
     * @return the status value.
     */
    public Status getStatus() {
        return this.status;
    }
}
