// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for Code. */
public final class Code extends ExpandableStringEnum<Code> {
    /** Static value InvalidRequest for Code. */
    public static final Code INVALID_REQUEST = fromString("InvalidRequest");

    /** Static value InvalidArgument for Code. */
    public static final Code INVALID_ARGUMENT = fromString("InvalidArgument");

    /** Static value Unauthorized for Code. */
    public static final Code UNAUTHORIZED = fromString("Unauthorized");

    /** Static value Forbidden for Code. */
    public static final Code FORBIDDEN = fromString("Forbidden");

    /** Static value NotFound for Code. */
    public static final Code NOT_FOUND = fromString("NotFound");

    /** Static value ProjectNotFound for Code. */
    public static final Code PROJECT_NOT_FOUND = fromString("ProjectNotFound");

    /** Static value OperationNotFound for Code. */
    public static final Code OPERATION_NOT_FOUND = fromString("OperationNotFound");

    /** Static value AzureCognitiveServiceNotFound for Code. */
    public static final Code AZURE_COGNITIVE_SERVICE_NOT_FOUND = fromString("AzureCognitiveServiceNotFound");

    /** Static value AzureCognitiveSearchIndexNotFound for Code. */
    public static final Code AZURE_COGNITIVE_SEARCH_INDEX_NOT_FOUND = fromString("AzureCognitiveSearchIndexNotFound");

    /** Static value TooManyRequests for Code. */
    public static final Code TOO_MANY_REQUESTS = fromString("TooManyRequests");

    /** Static value AzureCognitiveSearchThrottling for Code. */
    public static final Code AZURE_COGNITIVE_SEARCH_THROTTLING = fromString("AzureCognitiveSearchThrottling");

    /** Static value AzureCognitiveSearchIndexLimitReached for Code. */
    public static final Code AZURE_COGNITIVE_SEARCH_INDEX_LIMIT_REACHED =
            fromString("AzureCognitiveSearchIndexLimitReached");

    /** Static value InternalServerError for Code. */
    public static final Code INTERNAL_SERVER_ERROR = fromString("InternalServerError");

    /** Static value ServiceUnavailable for Code. */
    public static final Code SERVICE_UNAVAILABLE = fromString("ServiceUnavailable");

    /**
     * Creates or finds a Code from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding Code.
     */
    @JsonCreator
    public static Code fromString(String name) {
        return fromString(name, Code.class);
    }

    /**
     * Gets known Code values.
     *
     * @return known Code values.
     */
    public static Collection<Code> values() {
        return values(Code.class);
    }
}
