// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.language.textanalytics.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Unexpected error. */
@Immutable
public final class ErrorResponse {
    /*
     * Document error.
     */
    @JsonProperty(value = "error", required = true, access = JsonProperty.Access.WRITE_ONLY)
    private Error error;

    /**
     * Creates an instance of ErrorResponse class.
     *
     * @param error the error value to set.
     */
    @JsonCreator
    public ErrorResponse(
            @JsonProperty(value = "error", required = true, access = JsonProperty.Access.WRITE_ONLY) Error error) {
        this.error = error;
    }

    /**
     * Get the error property: Document error.
     *
     * @return the error value.
     */
    public Error getError() {
        return this.error;
    }
}
