// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

module com.cadl.testserver {
    requires transitive com.azure.core;

    exports com.cadl.testserver;
    exports com.cadl.testserver.models;

    opens com.cadl.testserver.models to
            com.azure.core,
            com.fasterxml.jackson.databind;
}
